/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package shift2dgrid;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;

import com.google.common.collect.Lists;

public class App {

    private static List<List<Integer>> shiftGrid(int[][] grid, int k){
        //List<Integer> list = Arrays.stream(grid).flatMapToInt(o -> Arrays.stream(o)).boxed().collect(Collectors.toList());
        var list = new ArrayList<Integer>();
        Arrays.stream(grid).forEach(row -> Arrays.stream(row).forEach(list::add));
        List<List<Integer>> result = new ArrayList<List<Integer>>();
        int w = grid[0].length;
        
        for(int i = 0;i < k;i++){
            list.add(0,list.get(list.size()-1));
            list.remove(list.size()-1);    
        }

        //System.out.println(t);
        for(int i = 0;i < grid.length;i++){
            result.add(list.subList(i*w, (i+1)*w));
        }        
        return result;               
    }

    public static List<List<Integer>> shiftGrid1(int[][] grid,int k){
        var pockets = new ArrayList<Integer>();
        var list = new ArrayList<Integer>();
        List<List<Integer>> result = new ArrayList<List<Integer>>();

        Arrays.stream(grid).forEach(row -> {
            pockets.add(row.length);
            Arrays.stream(row).forEach(list::add);
        });        


        for(int i = 0;i < k;i++){
            list.add(0,list.get(list.size()-1));
            list.remove(list.size()-1);
        }

        int s = 0;
        for(int i = 0;i < pockets.size();i++){

            result.add(list.subList(s, s+pockets.get(i)));
            s+=pockets.get(i);
        }
        return result;
    }

    public static void main(String[] args) {
        int[][] grid3 = {
            {1,2,3,1},
            {4,5,6},
            {7,8,9,3},
            {2,3}};

        System.out.println(Arrays.deepToString(grid3));
        System.out.println(shiftGrid1(grid3, 3));

        // System.out.println(Arrays.deepToString(grid3));        
        // System.out.println(shiftGrid(grid3, 100));
    }
}
